config/routes.rb
Rails.application.routes.draw do

  # mount ForestLiana::Engine => '/forest'
  ActiveAdmin.routes(self)

  # ROOT TO LANDING WEBSITE
  if Rails.env.development?
    devise_scope :user do
      root to: 'devise/sessions#new'
    end
  else
    root to: redirect("http://cforgood.com")
  end

  get 'notre_charte',             to: 'pages#charte'
  get 'cgu',                      to: 'pages#cgu'
  get 'faq_connect',              to: 'pages#faq_connect'
  put 'newsletter',               to: 'pages#newsletter'

  resources :contact_forms, only: [:new, :create]

  # ROOT TO APP CFORGOOD
  resources :businesses, only: [:index, :show]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', passwords: :passwords }, path: '', path_names: {:sign_in => 'signin', :sign_up => 'signup'}
  devise_scope :user do
    get 'signin',                   to: 'devise/sessions#new'
    post 'signin',                  to: 'devise/sessions#create'
    get 'signup',                   to: 'devise/registrations#new'
    post 'signup',                  to: 'devise/registrations#create'
    get 'signup_trial',             to: 'devise/registrations#new_gift'
    post 'signup_trial',            to: 'devise/registrations#create_gift'
    get 'signup_gift',              to: 'devise/registrations#new_gift'
    post 'signup_gift',             to: 'devise/registrations#create_gift'
    get 'signup_beneficiary',       to: 'devise/registrations#new_gift'
    post 'signup_beneficiary',      to: 'devise/registrations#create_gift'
    get "member/sent_mail",         to: "devise/passwords#sent_mail"
    put "member/update_cause",      to: "member/registrations#update_cause"
    put "member/update_profile",    to: "member/registrations#update_profile"
    put "member/stop_subscription", to: "member/registrations#stop_subscription"
  end

  namespace :member do
    resources :users, only: [:show, :update] do
      get "dashboard",  to: "dashboard#dashboard"
      get "profile",    to: "dashboard#profile"
      get "ambassador", to: "dashboard#ambassador"
      get "gift",       to: "dashboard#gift"
    end
    get "subscribe_gift", to: "subscribe#gift"
    resources :subscribe, only: [:new, :create, :update, :destroy]
    resources :perks, only: [:show]
  end

  get "map", to: "member/dashboard#dashboard"

  resources :users do
    resources :beneficiaries, only: [:create, :update]
  end

  devise_for :businesses, path: :pro, controllers: { passwords: :passwords }
  devise_scope :business do
    get "pro/sent_mail",        to: "devise/passwords#sent_mail"
    put "pro/update_business",  to: "pro/registrations#update_business"
  end

  namespace :pro do
    resources :businesses, only: [:show, :update, :new, :create] do
      resources :addresses
      resources :perks, only: [:index, :new, :create, :update]
      get 'dashboard',  to: 'dashboard#dashboard'
      post 'impersonation', to: 'dashboard#set_impersonation'
      get "profile",    to: "dashboard#profile"
      get "supervisor_dashboard", to: "dashboard#supervisor_dashboard"
    end
    resources :perks, only: [:show, :edit, :update, :destroy]
    resources :addresses, only: [:update]

    resources :activate, only: [:update, :destroy]
  end

  # namespace :asso do
  resources :causes, only: [:index, :show]
  #   get 'dashboard', to: 'dashboard#dashboard'
  # end

  resources :perks do
    resources :uses, only: [:create, :update]
  end

  resources :addresses do
    resources :timetables, only: [:create, :update]
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/businesses_controller.rb
# == Schema Information
#
# Table name: businesses
#
#  id                     :integer          not null, primary key
#  name                   :string
#  street                 :string
#  zipcode                :string
#  city                   :string
#  url                    :string
#  telephone              :string
#  email                  :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  description            :text
#  business_category_id   :integer
#  latitude               :float
#  longitude              :float
#  facebook               :string
#  twitter                :string
#  instagram              :string
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  leader_first_name      :string
#  leader_last_name       :string
#  leader_description     :text
#  active                 :boolean          default(FALSE), not null
#  online                 :boolean          default(FALSE), not null
#  leader_phone           :string
#  leader_email           :string
#  shop                   :boolean          default(TRUE), not null
#  itinerant              :boolean          default(FALSE), not null
#  picture                :string
#  leader_picture         :string
#  logo                   :string
#
# Indexes
#
#  index_businesses_on_business_category_id  (business_category_id)
#  index_businesses_on_email                 (email) UNIQUE
#  index_businesses_on_reset_password_token  (reset_password_token) UNIQUE
#

class BusinessesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @businesses = Business.active.joins(:perks).active.distinct.includes(:business_category)
    @addresses_id = []
    @businesses.each do |business|
      # @addresses_id << [business.id, 0] # BUSINESS MAIN ADDRESS
      business.addresses.shop.each do |address_shop|
        @addresses_id << [business.id, address_shop.id]
      end
      if business.itinerant
        business.addresses.active.today.each do |address_itinerant|
           @addresses_id << [business.id, address_itinerant.id]
        end
      end
    end
    @addresses_id.delete([]) # REMOVE WHEN NO ACTIVE RECORD ASSOCIATION
  end

  def businesses_index
    @businesses = Business.all
  end

  def show
    @business = Business.joins(:business_category).find(params[:id])
    @perk = @business.perks.find(params[:perk_id])

    if params[:address_id].to_i > 0
      @address = @business.addresses.find(params[:address_id])
      longitude = @address.longitude
      latitude = @address.latitude
    else
      longitude = @business.longitude
      latitude = @business.latitude
    end

    @geojson = {"type" => "FeatureCollection", "features" => []}

    @geojson["features"] << {
      "type": 'Feature',
      "geometry": {
        "type": 'Point',
        "coordinates": [longitude, latitude],
      },
      "properties": {
        "marker-symbol": @business.business_category.marker_symbol,
        "color": @business.business_category.color
      }
    }
    respond_to do |format|
      format.html
      format.json{render json: @geojson}
    end
  end
end

app/controllers/pro/businesses_controller.rb
class Pro::BusinessesController < Pro::ProController

  skip_after_action :verify_authorized

  def new
    if current_impersonation
      @error = "Vous essayez de créer un commerce, nous vous avons déconnecté de #{current_impersonation.name}"
    end
    session[:impersonate_id] = nil
    @business = Business.new
  end

  def create
    @business = current_business.businesses.build(business_params)
    @business.password = 'cforgood'
    if @business.save
      session[:impersonate_id] = @business.id
      redirect_to pro_business_profile_path(current_business)
    else
      @error = "Echec de la création du commerce"
      render :new
    end
  end

  private

  def business_params
    params.require(:business).permit(:name, :email, :city, :zipcode, :business_category_id)
  end
end

app/views/businesses/_business_search_index.html.erb
<div class="business-search-index-js hidden">

  <div class="business-search-close-button">
    <div>Annuler la recherche</div>
  </div>

  <div class="bsmd-container-mobile">
    <div id="business-search-modal">

      <ul class="list">
        <% @businesses.each do |business| %>
          <div class="business-index-card">
            <div class="bic-left">
              <div class="bic-photo" style="background-image: url('<%= business.picture %>');"></div>
            </div>
            <div class="bic-middle">
              <div class="bic-middle-top">
                <div class="business-name"><%= business.name %></div>
              </div>
              <div class="bic-middle-bottom">
                <div class="little-perk-logo" style="background-color:<%= business.business_category.color %> ">
                  <%= image_tag business.business_category.picture, size: "10x10" %>
                </div>
                <div class="category-name category" style="color: grey;"><%= business.business_category.name %></div>
              </div>
            </div>
            <div class="bic-right">
              <div>+</div>
            </div>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<% content_for :modal_search_index do %>

  <script>

    var options = {
      valueNames: [ 'business-name' ]
    };

    var userList = new List('business-search-modal', options);

    $('#search-in-navbar-mobile').keyup(function(){
      userList.search($(this).val());
    });

  </script>

<% end %>

app/views/businesses/_business_search_index_desk.html.erb
<div class="business-search-index-js-desk hidden">

  <div class="text-count-container">
    <div class="text-count"></div>
  </div>

  <div class="bsmd-container">
    <div id="business-search-modal-desktop">
      <ul class="list">
        <% @businesses.each do |business| %>
          <div class="business-index-card">
            <div class="bic-left">
              <div class="bic-photo" style="background-image: url('<%= business.picture %>');"></div>
            </div>
            <div class="bic-middle">
              <div class="bic-middle-top">
                <div class="business-name-desk"><%= business.name %></div>
              </div>
              <div class="bic-middle-bottom">
                <div class="little-perk-logo" style="background-color:<%= business.business_category.color %> ">
                  <%= image_tag business.business_category.picture, size: "10x10" %>
                </div>
                <div class="category-name category" style="color: grey;"><%= business.business_category.name %></div>
              </div>
            </div>
            <div class="bic-right">
              <div>+</div>
            </div>
          </div>
        <% end %>
      </ul>
    </div>
  </div>

</div>

<% content_for :modal_search_index_desk do %>

  <script>

    var options = {
      valueNames: [ 'business-name-desk' ]
    };

    var userList = new List('business-search-modal-desktop', options);

    $('#search-dashboard').keyup(function(){
      userList.search($(this).val());
    });

  </script>

<% end %>

app/views/businesses/_businesses_count.html.erb
<h2>
  <%= pluralize(businesses_count, "result") %>
</h2>

app/views/businesses/_mobileshow.html.erb
<div class="perk-modal-mobile hidden">
  <div class="perk-modal-close-mobile">
    <i class="fa fa-times" aria-hidden="true"></i>
  </div>

  <div class="perk-modal-header">
    <div class="perk-modal-icon"></div>
    <div class="perk-modal-header-text">REJOIGNEZ LA REVOLUTION POSITIVE</div>
  </div>

  <div class="perk-modal-title-dotted">
    <div class="perk-modal-yellow-dot">
      <div>1</div>
    </div>
    <div class="perk-modal-title-text">Découvrez votre ville autrement</div>
  </div>

  <div class="perk-modal-description">
    Je trouve de nouveaux commerçants responsables, des associations engageés et des événements enthousiasmant chez moi ou dans les autres villes où je me rends.
  </div>


  <div class="perk-modal-title-dotted">
    <div class="perk-modal-yellow-dot">
      <div>2</div>
    </div>
    <div class="perk-modal-title-text">J'accède à des reductions exclusives</div>
  </div>

  <div class="perk-modal-description">
    Je trouve de nouveaux commerçants responsables, des associations engageés et des événements enthousiasmant chez moi ou dans les autres villes où je me rends.
  </div>


  <div class="perk-modal-title-dotted">
    <div class="perk-modal-yellow-dot">
      <div>3</div>
    </div>
    <div class="perk-modal-title-text">Je rejoins une véritable révolution</div>
  </div>

  <div class="perk-modal-description">
    Je trouve de nouveaux commerçants responsables, des associations engageés et des événements enthousiasmant chez moi ou dans les autres villes où je me rends.
  </div>

  <div class="perk-modal-button-signup">
    <div class="perk-signin-button">JE M'INSCRIS</div>
  </div>

</div>

app/views/businesses/index.html.erb
<%= content_for(:title) do %>
  Bons Plans
<% end %>
<%= content_for(:description) do %>
  Découvrez notre liste de bons plans
<% end %>

<div class="container-fluid admin">
  <!-- Sub Menu Sidebar -->
  <%= render "member/dashboard/shared/sidebar" %>
  <!-- Content - Statistics -->
  <div class="dashboard dashboard-view-perks">
    <div class="mobile-menu-overlay hidden"></div>

    <%= render "components/menu/index_search_category" %>

    <div class="search-category-overlay hidden"></div>
      <div id="businesses">
        <div id="mixitup" class="container-perk-cards">

        <ul class="list">
          <% @businesses.each do |business| %>
            <% (@addresses_id.select { |address_id| address_id[0] == business.id }).each do |address_id| %>
              <!-- COMPONENT | ADDRESSES -->
              <% business.perks.active.each do |perk| %>
                <!-- COMPONENT | CARD BON PLAN -->
                <%= link_to business_path(business, perk_id: perk.id, address_id: address_id[1]), class: "card-frame mix #{business.business_category_id} #{business.online? ? 'online' : ''}" do %>
                  <!-- CARD HEADER -->
                  <div class="card-header">
                    <h3 class="perk-name name hidden"><%= perk.name %></h3>
                    <div class="card-header-main">
                      <span class="perk-title"><%= business.name %></span>
                      <% liked = Use.liked.where(perk_id: perk.id).count %>
                      <% if liked > 0 %>
                      <div class="perk-liked">
                        <%= render 'shared/icons/heart_like' %>
                        <span><%= liked %></span>
                      </div>
                      <% end %>
                    </div>
                    <div class="card-header-leader">
                    <% if business.leader_picture.present? %>
                      <%= image_tag business.leader_picture.url(:avatar) %>
                    <% else %>
                      <%= image_tag image_url 'default_pic.png' %>
                    <% end %>
                    </div>
                    <div class="card-header-category" style="background-color: <%= business.business_category.color %>;">
                      <%= image_tag business.business_category.picture %>
                      <!-- <div class="category-container" style="background-color: <#= business.business_category.color %>;">
                      </div> -->
                    </div>
                  </div>
                  <!-- CARD BODY -->
                  <div class="card-body" style="background-image: url('<%= perk.picture.present? ? perk.picture.url(:card) : business.picture.url(:card) %>');">
                    <div class="business-details">
                      <% if perk.flash? && perk.times > 0 %>
                        <span style="background-color: <%= business.business_category.color %>;"><i class="fa fa-flash"></i><%= perk.times - Use.used.where(perk_id: perk.id).count  %> restants</span>
                      <% end %>
                      <h3 class="perk-name name"><%= perk.name %></h3>
                    </div>
                  </div>
                <% end %>
                <!-- END | CARD BON PLAN -->
              <% end %>
              <!-- END | ADDRESSES -->
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  <!-- END | DASHBOARD PERKS -->
  </div>
  <!-- END | ADMIN -->
</div>

<% content_for :after_js do %>

  <script>

    $(document).ready(function(){

      // TOOGLE CATEGORY MENUs
      $('#open-categories').click(function(event) {
        $('.search-category-overlay').toggleClass('hidden');
        // TOOGLE CATEGORY MENU
        $('.search-category').toggleClass('is-open-max');
        $('.category-item').toggleClass('is-open-min');
      });

      // TOOGLE CATEGORY OVERLAY
      $('.search-category-overlay').click(function(event) {
        $(this).addClass('hidden');
        $('.search-category').removeClass('is-open-max');
        $('.category-item').removeClass('is-open-min');
      });

      // EVENT AMPLITUDE USER_ALL_PERKS + USER_C_BUSINESS_ALLPERKS
      amplitude.logEvent('USER_ALL_PERKS');
      $('.card-frame').click(function(event) {
        amplitude.logEvent('USER_C_BUSINESS_ALLPERKS');
      });

    });

    var buttonFilter = {
      // Declare any variables we will need as properties of the object
      $filters: null,
      $reset: null,
      groups: [],
      outputArray: [],
      outputString: '',

      // The "init" method will run on document ready and cache any jQuery objects we will need.
      init: function(){
        var self = this; // As a best practice, in each method we will asign "this" to the variable "self" so that it remains scope-agnostic. We will use it to refer to the parent "buttonFilter" object so that we can share methods and properties between all parts of the object.

        self.$filters = $('#Filters');
        self.$reset = $('#categories-all');
        self.$container = $('#mixitup');
        self.$filters.find('.fieldset-flexbox').each(function(){
          self.groups.push({
            $buttons: $(this).find('.filter-btn'),
            active: ''
          });
        });
        self.bindHandlers();
      },

      // The "bindHandlers" method will listen for whenever a button is clicked.
      bindHandlers: function(){
        var self = this;

        // Handle filter clicks
        self.$filters.on('click', '.filter-btn', function(e){
          e.preventDefault();
          var $button = $(this);

          // If the button is active, remove the active class, else make active and deactivate others.
          $button.hasClass('is-selected') ?
            $button.removeClass('is-selected') :
            $button.addClass('is-selected').siblings('.filter-btn').removeClass('is-selected');

          self.parseFilters();
        });

        // Handle reset click
        self.$reset.on('click', function(e){
          e.preventDefault();
          self.$filters.find('.filter-btn').removeClass('is-selected');
          self.parseFilters();
        });
      },

      // The parseFilters method checks which filters are active in each group:
      parseFilters: function(){
        var self = this;

        // loop through each filter group and grap the active filter from each one.
        for(var i = 0, group; group = self.groups[i]; i++){
          group.active = group.$buttons.filter('.is-selected').attr('data-filter') || '';
        }

        self.concatenate();
      },

      // The "concatenate" method will crawl through each group, concatenating filters as desired:
      concatenate: function(){
        var self = this;

        self.outputString = ''; // Reset output string

        for(var i = 0, group; group = self.groups[i]; i++){
          self.outputString += group.active;
        }

        // If the output string is empty, show all rather than none:
        !self.outputString.length && (self.outputString = 'all');

        // Send the output string to MixItUp via the 'filter' method:
        if(self.$container.mixItUp('isLoaded')){
          self.$container.mixItUp('filter', self.outputString);
        }
      }
    };

    // On document ready, initialise our code.
    $(function(){
      // Initialize buttonFilter code
      buttonFilter.init();
      // Instantiate MixItUp
      $('#mixitup').mixItUp({
        controls: {
          enable: true // we won't be needing these
        },
        animationOptions: {
          duration: 750,
          easing: 'linear',
          queue: false
        }
      });
    });

    // var monkeyList = new List('perks-list', {
    //   valueNames: ['perk-name'],
    //   plugins: [ ListFuzzySearch() ]
    // });

    // var options = {
    //   valueNames: [ 'perk-name' ]
    // };

    // var perksList = new List('perks-list', options);

  </script>

<% end %>

<% content_for :listjs_businesses do %>

  <script>

    var options = {
      valueNames: [ 'perk-title' ]
    };

    var userList = new List('businesses', options);

    $('#search-businesses').keyup(function(){
      userList.search($(this).val());
    });

  </script>

<% end %>

app/views/businesses/save_show.html.erb
<% content_for :meta_title, @business.name %>
<% content_for :meta_description, "Découvrez le Bon Plan offert par #{@business.name} !" %>
<% content_for :meta_image, @perk.picture.present? ? @perk.picture : @business.picture %>

<%= render "member/dashboard/shared/sidebar" %>

<div class="fullpage">

<<<<<<< HEAD
  <div class="fullpage-left-item">
    <div class="colored-banner" style="background-color: <%= @business.business_category.color %>;">
      <div class="banner-business-name">
        <div class="name"><%= @business.name %></div>
      </div>
      <div class="banner-business-top-infos">
        <div class="infos-left">
          <div class="little-perk-logo">
            <%= image_tag @business.business_category.picture, size: "10x10" %>
=======
          <!-- IF FLASH PERK -->
          <% if @perk.flash? %>
            <% if @perk.times > 0 %>
              <span class="flash-notification" style="background-color: <%= @business.business_category.color %>;"><i class="fa fa-flash"></i><%= @perk.times - Use.used.where(perk_id: params[:perk_id]).count %> restants</span>
            <% end %>
            <span class="availabilities"><%= render(partial: "components/perk_flash_period", locals: { start_date: @perk.start_date, end_date: @perk.end_date }) %></span>
          <% end %>
          <h1><%= @perk.name %></h1>
          <p><%= @perk.description %></p>
            <div class="use-perk">
            <% if user_signed_in? %>
              <% if !@perk.perk_in_time? %>
                <div id="button-used">
                  <button class="empty">Bon plan non disponible</button>
                </div>
              <% elsif !@perk.perk_usable?(current_user) %>
                <div id="button-used">
                  <button class="empty">Bon plan épuisé</button>
                </div>
              <% else %>
                 <button type="button" class="use-button" style="background-color: <%= @business.business_category.color %>;">J'en profite</button>
              <% end %>
            <% else %>
              <button type="button" class="use-button-logout" style="background-color: <%= @business.business_category.color %>;">J'en profite</button>
              <%#= link_to "J'en profite", new_member_subscribe_path, class: "btn btn-use-button btn-block" %>
            <% end %>
>>>>>>> master
          </div>
          <div class="category-name category"><%= @business.business_category.name %></div>
        </div>
        <div class="infos-right">
          <div class="dot-state"></div>
          <div class="dot-state-name">Ouvert</div>
        </div>
      </div>
      <div class="card-abs-banner">
        <div class="card-photo" style="background-image: url('<%= @business.picture %>');"></div>
        <div class="card-bottom-links">
          <div class="card-bottom-left-item" style="background-color: <%= @business.business_category.color %>;">
            <div class="card-red-heart">
              <i class="fa fa-heart" aria-hidden="true"></i>
            </div>
            <div class="firstblock-text"><%= "63 personnes" %></div>
          </div>
          <div class="card-bottom-right-item" style="background-color: <%= @business.business_category.color %>;">
       <!--      <div class="cbri-firstblock hidden-xs">
              <div class="firstblock-text">Partager :</div>
            </div> -->
            <div class="cbri-middleblock">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </div>
            <div class="cbri-endblock">
              <i class="fa fa-twitter" aria-hidden="true"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
<<<<<<< HEAD
    <div class="fullpage-left-item-bottom">
      <div class="">
        <div class="title-sub">Leurs engagements</div>
      </div>
      <div class="flib-engages">
        <div class="flib-engages-item">
          <div class="flib-icon"></div>
          <div class="flib-text">Eco-responsable</div>
        </div>
        <div class="flib-engages-item">
          <div class="flib-icon"></div>
          <div class="flib-text">Zéro déchets</div>
=======
  </div>
</div><!-- END SHOW MOBILE -->

  <div class="show-desktop">
    <!-- COLUMN LEFT -->
    <div class="perk-details">
       <!-- BLOCK PERK -->
        <% if @perk.picture.present? %>
          <div class="perk-image" style="background-image: url('<%= @perk.picture %>');">
        <% else %>
          <div class="perk-image" style="background-image: url('<%= @business.picture %>');">
        <% end %>

        <!-- IF FLASH PERK -->
        <% if @perk.flash? %>
          <% if @perk.times > 0 %>
            <span class="flash-notification" style="background-color: <%= @business.business_category.color %>;"><i class="fa fa-flash"></i><%= @perk.times - Use.used.where(perk_id: params[:perk_id]).count %> restants</span>
          <% end %>
          <span class="availabilities"><%= render(partial: "components/perk_flash_period", locals: { start_date: @perk.start_date, end_date: @perk.end_date }) %></span>
        <% end %>
        <h1><%= @perk.name %></h1>
        <p><%= @perk.description %></p>
        <div class="use-perk">
          <% if user_signed_in? %>
            <% if !@perk.perk_in_time? %>
              <div id="button-used">
                <button class="empty">Bon plan non disponible</button>
              </div>
            <% elsif !@perk.perk_usable?(current_user) %>
              <div id="button-used">
                <button class="empty">Bon plan épuisé</button>
              </div>
            <% else %>
              <button type="button" class="use-button" style="background-color: <%= @business.business_category.color %>;">J'en profite</button>
            <% end %>
          <% else %>
            <button type="button" class="use-button-logout" style="background-color: <%= @business.business_category.color %>;">J'en profite</button>
            <%#= link_to "J'en profiterai bien", new_member_subscribe_path, class: "btn btn-use-button btn-block" %>
          <% end %>
>>>>>>> master
        </div>
        <div class="flib-engages-item">
          <div class="flib-icon"></div>
          <div class="flib-text">Circuit court</div>
        </div>
      </div>
      <div class="">
        <div class="title-sub">En quelques mots</div>
      </div>
      <% if @business.description.present? %>
        <div class="business-desc">
          <%= @business.description %>
        </div>
      <% else %>
        <div class="business-desc">Profil en construction</div>
      <% end %>
      <div class="">
        <div class="title-sub">Informations</div>
      </div>
    </div>
  </div>

  <div class="fullpage-right-item hidden-xs">
    <div class="fri-header">
      <div class="biz-avatar" style="background-image: url('<%= @business.business_category.picture %>');"></div>
      <div class="title-sub" style="margin-bottom: 0px;">Nos bons plans</div>
    </div>
    <div class="perk-card-container">
      <div class="perk-card">
        <div class="perk-card-left-item" style="background-color: <%= @business.business_category.color %>;">
          <div class="perk-card-absolute-photo"></div>
        </div>
        <div class="perk-card-right-item">
          <div class="pcri-container">
            <div class="pcri-item">
              <div class="pcri-item-tooltip" style="background-color: <%= @business.business_category.color %>;">
                <div>OFFERT</div>
              </div>
            </div>
            <div class="pcri-second-item">
              <div class="pcri-si-text">DEUX CONTENANTS OFFERTS</div>
            </div>
            <div class="perk-pseudo-modal-link">J'EN PROFITE</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<<<<<<< HEAD
<div class="perk-modal hidden">
  <div class="perk-modal-close">
    <i class="fa fa-times" aria-hidden="true"></i>
  </div>

  <div class="perk-modal-header">
    <div class="perk-modal-icon"></div>
    <div class="perk-modal-header-text">REJOIGNEZ LA REVOLUTION POSITIVE</div>
  </div>

  <div class="perk-modal-title-dotted">
    <div class="perk-modal-yellow-dot">
      <div>1</div>
    </div>
    <div class="perk-modal-title-text">Découvrez votre ville autrement</div>
  </div>

  <div class="perk-modal-description">
    Je trouve de nouveaux commerçants responsables, des associations engageées et des événements enthousiasmant chez moi ou dans les autres villes où je me rends.
  </div>


  <div class="perk-modal-title-dotted">
    <div class="perk-modal-yellow-dot">
      <div>2</div>
    </div>
    <div class="perk-modal-title-text">J'accède à des reductions exclusives</div>
  </div>

  <div class="perk-modal-description">
    Je trouve de nouveaux commerçants responsables, des associations engageées et des événements enthousiasmant chez moi ou dans les autres villes où je me rends.
  </div>


  <div class="perk-modal-title-dotted">
    <div class="perk-modal-yellow-dot">
      <div>3</div>
    </div>
    <div class="perk-modal-title-text">Je rejoins une véritable révolution</div>
  </div>

  <div class="perk-modal-description">
    Je trouve de nouveaux commerçants responsables, des associations engageées et des événements enthousiasmant chez moi ou dans les autres villes où je me rends.
  </div>

<<<<<<< HEAD
  <div class="perk-modal-button-signup">
    <div class="perk-signin-button">JE M'INSCRIS</div>
  </div>
=======
      $(".use-button-logout").click(function() {
        $('.use-overlay').removeClass('hidden');
        // EVENT AMPLITUDE USER_C_BENEFIT
        amplitude.logEvent('USER_C_BENEFIT_LOGOUT');
      });

      $(".btn-use-button").click(function() {
        // EVENT AMPLITUDE USER_C_BENEFIT
        amplitude.logEvent('USER_C_BENEFIT');
      });
>>>>>>> master

</div>

<div class="fixed-bottom-container-button">
  <div class="fixed-bottom-perk-link" style="border-top: 2px solid <%= @business.business_category.color %> ;">
    <% if !current_user.member %>
    <div class="see-perk-button perk-pseudo-modal-link-mobile-member" style="background-color: <%= @business.business_category.color %>;">Voir nos bons plans</div>
    <% else %>
    <div class="see-perk-button perk-pseudo-modal-link-mobile" style="background-color: <%= @business.business_category.color %>;">Voir nos bons plans</div>
    <% end %>
  </div>
</div>

<%= render "businesses/mobileshow" %>

<%= render "businesses/mobileshow_member" %>