config/routes.rb
Rails.application.routes.draw do

  # mount ForestLiana::Engine => '/forest'
  ActiveAdmin.routes(self)

  # ROOT TO LANDING WEBSITE
  if Rails.env.development?
    devise_scope :user do
      root to: 'devise/sessions#new'
    end
  else
    root to: redirect("http://cforgood.com")
  end

  get 'notre_charte',             to: 'pages#charte'
  get 'cgu',                      to: 'pages#cgu'
  get 'faq_connect',              to: 'pages#faq_connect'
  put 'newsletter',               to: 'pages#newsletter'

  resources :contact_forms, only: [:new, :create]

  # ROOT TO APP CFORGOOD
  resources :businesses, only: [:index, :show]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', passwords: :passwords }, path: '', path_names: {:sign_in => 'signin', :sign_up => 'signup'}
  devise_scope :user do
    get 'signin',                   to: 'devise/sessions#new'
    post 'signin',                  to: 'devise/sessions#create'
    get 'signup',                   to: 'devise/registrations#new'
    post 'signup',                  to: 'devise/registrations#create'
    get 'signup_trial',             to: 'devise/registrations#new_gift'
    post 'signup_trial',            to: 'devise/registrations#create_gift'
    get 'signup_gift',              to: 'devise/registrations#new_gift'
    post 'signup_gift',             to: 'devise/registrations#create_gift'
    get 'signup_beneficiary',       to: 'devise/registrations#new_gift'
    post 'signup_beneficiary',      to: 'devise/registrations#create_gift'
    get "member/sent_mail",         to: "devise/passwords#sent_mail"
    put "member/update_cause",      to: "member/registrations#update_cause"
    put "member/update_profile",    to: "member/registrations#update_profile"
    put "member/stop_subscription", to: "member/registrations#stop_subscription"
  end

  namespace :member do
    resources :users, only: [:show, :update] do
      get "dashboard",  to: "dashboard#dashboard"
      get "profile",    to: "dashboard#profile"
      get "ambassador", to: "dashboard#ambassador"
      get "gift",       to: "dashboard#gift"
    end
    get "subscribe_gift", to: "subscribe#gift"
    resources :subscribe, only: [:new, :create, :update, :destroy]
    resources :perks, only: [:show]
  end

  get "map", to: "member/dashboard#dashboard"

  resources :users do
    resources :beneficiaries, only: [:create, :update]
  end

  devise_for :businesses, path: :pro, controllers: { passwords: :passwords }
  devise_scope :business do
    get "pro/sent_mail",        to: "devise/passwords#sent_mail"
    put "pro/update_business",  to: "pro/registrations#update_business"
  end

  namespace :pro do
    resources :businesses, only: [:show, :update, :new, :create] do
      resources :addresses
      resources :perks, only: [:index, :new, :create, :update]
      get 'dashboard',  to: 'dashboard#dashboard'
      post 'impersonation', to: 'dashboard#set_impersonation'
      get "profile",    to: "dashboard#profile"
      get "supervisor_dashboard", to: "dashboard#supervisor_dashboard"
    end
    resources :perks, only: [:show, :edit, :update, :destroy]
    resources :addresses, only: [:update]

    resources :activate, only: [:update, :destroy]
  end

  # namespace :asso do
  resources :causes, only: [:index, :show]
  #   get 'dashboard', to: 'dashboard#dashboard'
  # end

  resources :perks do
    resources :uses, only: [:create, :update]
  end

  resources :addresses do
    resources :timetables, only: [:create, :update]
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/perk.rb
# == Schema Information
#
# Table name: perks
#
#  id                :integer          not null, primary key
#  name              :string
#  business_id       :integer
#  description       :text
#  times             :integer          default(0)
#  start_date        :datetime
#  end_date          :datetime
#  active            :boolean          default(TRUE), not null
#  perk_code         :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  nb_views          :integer          default(0)
#  appel             :boolean          default(FALSE), not null
#  durable           :boolean          default(FALSE), not null
#  flash             :boolean          default(FALSE), not null
#  perk_detail_id    :integer
#  deleted           :boolean          default(FALSE), not null
#  all_day           :boolean          default(FALSE), not null
#  picture           :string
#  text_notification :string
#  send_notification :boolean          default(FALSE)
#  offer             :boolean          default(FALSE), not null
#  value             :boolean          default(FALSE), not null
#  percent           :boolean          default(FALSE), not null
#  amount            :integer
#
# Indexes
#
#  index_perks_on_business_id     (business_id)
#  index_perks_on_perk_detail_id  (perk_detail_id)
#
# Foreign Keys
#
#  fk_rails_5797f2b98a  (business_id => businesses.id)
#

class Perk < ApplicationRecord

  belongs_to :business
  has_many :uses, dependent: :destroy
  belongs_to :perk_detail

  scope :active, -> { where(active: true) }
  scope :flash, -> { where(flash: true) }
  scope :undeleted, -> { where(deleted: false) }
  scope :permanent, -> { where('perks.active = ? and (perks.durable = ? or perks.appel = ?)', true, true, true) }
  scope :in_time, -> { where('perks.active = ? and (perks.durable = ? or perks.appel = ? or (perks.flash = ? and perks.start_date <= ? and perks.end_date >= ?))', true, true, true, true, Time.now, Time.now) }
  scope :flash_in_time, -> { where('perks.active = ? and perks.flash = ? and perks.start_date <= ? and perks.end_date >= ?', true, true, Time.now, Time.now) }

  extend TimeSplitter::Accessors
  split_accessor :start_date, :end_date

  validates :name, presence: true, length: { maximum: 35 }
  validate :name_uniqueness, if: :name_changed?
  validates :description, presence: true, length: { maximum: 220 }
  validates :perk_detail_id, presence: true
  validates :times, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_nil: true
  validate :dates_required_if_flash
  validate :start_date_cannot_be_greater_than_end_date
  validates :perk_code, length: { in: 5..15 }, format: { with: /\A[A-Za-z0-9]+\z/, message: "Le code du bon plan ne peut contenir que des lettres et des chiffres" }, if: :perk_code_needed?
  validate :perk_code_uniqueness, if: :perk_code_changed?

  validates_size_of :picture, maximum: 2.megabytes,
    message: "Cette image dépasse 2 MG !", if: :picture_changed?
  mount_uploader :picture, PictureUploader

  after_create :send_registration_slack, :update_data_intercom
  after_save :update_data_intercom, if: :active_changed?
  after_save :send_push_notification, if: :send_notification_changed?
  after_save :send_change_to_slack
  after_destroy :update_data_intercom

  def update_nb_view!
    self.increment!(:nb_views)
  end

  def perk_usable?(user)
    if self.durable
      true
    elsif self.appel
      user.uses.used.where(perk_id: self.id).count == 0
    elsif self.flash
      self.times == 0 || Use.used.where(perk_id: self.id).count < self.times
    end
  end

  def perk_in_time?
    if self.flash
      (self.start_date <= Time.now && self.end_date >= Time.now) && (self.times == 0 || Use.used.where(perk_id: self.id).count < self.times)
    else
      true
    end
  end

  def deleted!
    self.update(active: false, deleted: true)
  end

  private

  def perk_code_needed?
    name = PerkDetail.find(self.perk_detail_id).name
    name == "online" || name == "email"
  end

  def dates_required_if_flash
    if flash
      if !start_date.present?
        errors.add(:start_date, "La date de début est obligatoire pour un bon plan flash.")
      elsif all_day
        if end_date.present?
          self.start_date = start_date.change(hour: 0, min: 0)
          self.end_date = start_date.change(hour: 23, min: 59)
        elsif
          self.end_date = end_date.change(min: 0)
        end
      elsif !end_date.present?
        errors.add(:end_date, "La date de fin est obligatoire pour un bon plan flash.")
      end
    end
  end

  def start_date_cannot_be_greater_than_end_date
    if start_date.present? && end_date.present? && start_date > end_date
      errors.add(:end_date, "La date de fin ne doit pas être antérieure à la date de début.")
    end
  end

  def send_registration_slack
    message = "#{self.business.name} a créé un nouveau bon plan *" + perk_type(self.appel, self.durable, self.flash) + "* : #{name} : #{description}"
    send_message_to_slack(ENV['SLACK_WEBHOOK_PERK_URL'], message)
  end

  def send_change_to_slack
    if ( name_changed? && name_was.present? ) || ( description_changed? && description_was.present? )
      message = "#{self.business.name} a changé son bon plan *" + perk_type(self.appel, self.durable, self.flash) + "* : #{name} : #{description}"
      send_message_to_slack(ENV['SLACK_WEBHOOK_PERK_URL'], message)
    end
  end

  def name_uniqueness
    if name.present?
      name.upcase!
      errors.add(:name, "Ce nom de bon plan est déjà utilisé !") if Perk.where(name: self.name, deleted: false).where(business_id: self.business_id).count > 0
    end
  end

  def perk_code_uniqueness
    if perk_code.present?
      perk_code.upcase!
      errors.add(:perk_code, "Ce code n'est pas disponible !") if Perk.where(perk_code: self.perk_code, deleted: false).where(business_id: self.business_id).count > 0
    end
  end

  def update_data_intercom
    # UPDATE CUSTOM ATTRIBUTES ON INTERCOM
    intercom = Intercom::Client.new(app_id: ENV['INTERCOM_API_ID'], api_key: ENV['INTERCOM_API_KEY'])
    begin
      user = intercom.users.find(:user_id => 'B'+self.business_id.to_s)
      user.custom_attributes[:perks_all] = Business.find(self.business_id).perks.count
      user.custom_attributes[:perks_active] = Business.find(self.business_id).perks.active.count
      intercom.users.save(user)

      if :after_create
         intercom.events.create(
          event_name: "new-perk",
          created_at: Time.now.to_i,
          user_id: 'B'+self.business_id.to_s,
          email: self.business.email,
          metadata: {
            perk_id: self.id,
            perk_type: perk_type(self.appel, self.durable, self.flash),
            title: self.name,
            description: self.description,
            picture_url: self.picture.url,
            start_date: self.start_date,
            end_date: self.end_date,
            times: self.times
          }
        )
      end

    rescue Intercom::IntercomError => e
      puts e
    end
  end

  def send_push_notification

    if send_notification_changed? && send_notification
      params = {
        app_id: ENV['ONESIGNAL_APP_ID'],
        # template_id: '033eae5c-aa46-4e41-a3f7-f6cd4211a9fc',
        headings: {"en" => "Un tout nouveau bon plan pour #{self.business.name} 😊👏"},
        contents: {"en" => "#{self.text_notification}"},
        included_segments: ["All"],
        chrome_web_icon: self.picture.url(:thumb)
      }

      begin
        response = OneSignal::Notification.create(params: params)
        notification_id = JSON.parse(response.body)["id"]
      rescue OneSignal::OneSignalError => e
        puts "--- OneSignalError  :"
        puts "-- message : #{e.message}"
        puts "-- status : #{e.http_status}"
        puts "-- body : #{e.http_body}"
      end
    end
   end

  def active?
    if flash
      end_date < DateTime.now
    else
      active
    end
  end

  protected

  def perk_type(appel, durable, flash)
      return "BIENVENUE" if self.appel
      return "DURABLE" if self.durable
      return "FLASH" if self.flash
  end

end

app/controllers/pro/perks_controller.rb
class Pro::PerksController < Pro::ProController

  before_action :find_perk, only: [:edit, :update, :destroy]
  before_action :find_business, only: [:index, :new, :create, :edit]

  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def index
    if session[:impersonate_id]
      @perks = Perk.where(business_id: session[:impersonate_id]).undeleted
    else
      @perks = policy_scope(Perk).undeleted
    end
  end

  def new
    @perk = Perk.new
    authorize @perk
  end

  def create
    @perk = @business.perks.build(perk_params)
    authorize @perk

    respond_to do |format|
      if @perk.save
        format.html { redirect_to pro_business_perks_path(current_business) }
        format.js {}
      else
        format.html { render :new }
        format.js {}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @perk.update(perk_params)
        format.html { redirect_to pro_business_perks_path(current_business) }
        format.js {}
      else
        format.html { render :edit }
        format.js {}
      end
    end
  end

  def destroy
    if @perk.nb_views > 0 || @perk.uses.count > 0 || @perk.created_at < Date.today
      @perk.deleted!
    else
      @perk.destroy
    end
    redirect_to pro_business_perks_path(current_business)
  end

  private

  def find_perk
    @perk = Perk.find(params[:id])
    # authorize @perk
  end

  def find_business
    id = session[:impersonate_id] || params[:business_id] || current_business.id
    @business = Business.find(id)
  end

  def perk_params
    params.require(:perk).permit(:name, :description, :perk_detail_id, :times, :start_date, :start_date_date, :start_date_hour, :start_date_min, :end_date, :end_date_date, :end_date_hour, :end_date_min, :all_day, :perk_code, :picture, :active, :appel, :durable, :flash)
  end
end

app/views/pro/perks/modals/_perk_logout.html.erb
<div class="use-overlay hidden">
  <div class="flip-container-mobile flip-signin">
    <div class="flipper-mobile">
      <!-- FRONT CARD-->
      <figure class="front">
        <!-- CLOSE BUTTON-->
        <button type="button" class="close-button">&times;</button>
        <!-- ILLUSTRATION-->
        <div class="wrapper">
          <%= render "shared/icons/bowtie" %>
        </div>
        <!-- CTA-->
        <div class="container-code gentleman">
          <span>Hey !</span>
          <p>Ne manquez plus un seul bon plan !</p>
          <!-- SIGNUP/SIGNIN BUTTONS -->
          <%= link_to "S'inscrire", signup_path, class: "button-log sign-up" %>
          <%= link_to "Se connecter", "#" , class: "button-log sign-in" %>
        </div>
      </figure>
       <!-- BACK CARD -->
      <figure class="back">
        <!-- SIGNIN -->
        <div class="connexion popup-signin">
          <div class="sign-box">
            <!-- CLOSE BUTTON-->
            <button type="button" class="close-button-signin">&times;</button>
            <%= render "devise/sessions/shared/form_signin_logout", resource: User.new, resource_name: :user%>
          </div>
        </div>
      </figure>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>

  <script>

    $(document).ready(function() {

      $(".button-log.sign-in").click(function() {
        $('.flipper-mobile').toggleClass('flipped');
      });

       $(".close-button-signin").click(function() {
        $('.use-overlay').addClass('hidden');
        $('.flipper-mobile').toggleClass('flipped');
      });

    });

  </script>
<% end %>

app/views/pro/perks/modals/_perk_mailto.html.erb
<div class="use-overlay hidden">
  <div class="flip-container-mobile">
    <div class="flipper-mobile">
      <!-- FRONT CARD-->
      <figure class="front">
        <!-- CLOSE BUTTON-->
        <button type="button" class="close-button">&times;</button>
        <!-- ILLUSTRATION-->
        <div class="wrapper">
          <%= render "shared/icons/send_mail" %>
        </div>
        <span class="business-name"><%= @perk.business.name %></span>
        <div class="container-code">
          <p class="box-code-legend">Envoyez-nous un email pour réserver votre bon plan : </p>
        </div>
        <div class="itinary send-mail">
          <a href='mailto:<%= @business.email %>?subject=Nouvelle demande de bon plan CforGood !&body=Bonjour <%= @business.leader_first_name if @business.leader_first_name.present? %>,%0D%0A<%= @business.name %> semble sympa comme tout !%0D%0AJe souhaiterais bénéficier du bon plan « <%= Perk.find(params[:perk_id]).name.gsub(/%/, "%25").upcase %> » (Code : <%= Perk.find(params[:perk_id]).perk_code %>), pouvez-vous me dire comment procéder ?%0D%0A Merci par avance !%0D%0A<%= current_user.first_name.capitalize if current_user.first_name.present? %> <%= current_user.last_name.capitalize if current_user.last_name.present? %>' class="link-mail-business business-icon-container" target="_blank">
            <i class="fa fa-envelope"></i><abbr>Ecrivez-nous !</abbr>
          </a>
        </div>
        <div class="container-legend">
          <% if @perk.appel %>
            <p>Attention, ce bon plan n'est valable qu'une seule fois !</p>
          <% end %>
        </div>
        <%= simple_form_for :use, url: perk_uses_path(params[:perk_id], online: true), method: :post, remote: true, authenticity_token: true, html: { id: :create_use } do |f| %>
          <%= f.input :perk_id, as: :hidden, input_html: {value: params[:perk_id]} %>
          <%= f.submit "J'utilise", class: "btn-create-use", :style => "display: none;" %>
        <% end %>
      </figure>
      <!-- BACK CARD -->
      <figure class="back">
        <div class="container-feedback"></div>
      </figure>
    </div>
  </div>
</div>

<% content_for :after_js do %>
  <script>
    $(document).ready(function(){

      $('.send-mail').click(function() {
        $('.btn-create-use').click();
      });

    });
  </script>
<% end %>

app/views/pro/perks/modals/_perk_not_member.html.erb
<div class="use-overlay hidden">
  <div class="flip-container-mobile">
    <div class="flipper-mobile">
      <!-- FRONT CARD-->
      <figure class="front">
        <!-- CLOSE BUTTON-->
        <button type="button" class="close-button">&times;</button>
        <!-- ILLUSTRATION-->
        <div class="wrapper">
          <%= render "shared/icons/bowtie" %>
        </div>
        <!-- CTA-->
        <div class="container-code gentleman">
          <span>Oh mince...</span>
          <p>Ne manquez plus un seul bon plan en devenant membre CforGood !</p>
          <%= link_to "Je vous rejoins", member_user_profile_path(current_user, anchor: 'subscription'), class: "button-gentleman" %>
        </div>
      </figure>
    </div>
  </div>
</div>

app/views/pro/perks/modals/_perk_offline_desktop.html.erb
<div class="use-overlay hidden">
  <div class="flip-container-mobile">
    <div class="flipper-mobile">
      <!-- FRONT CARD-->
      <figure class="front">
        <!-- CLOSE BUTTON-->
        <button type="button" class="close-button">&times;</button>
        <!-- ILLUSTRATION-->
        <div class="wrapper">
          <%= render "shared/icons/backpack" %>
        </div>
        <!-- CTA -->
        <span class="business-name"><%= @perk.business.name %></span>
        <div class="itinary">
          <%= link_to "http://maps.google.com/maps", class: "", id:"link-map", disabled: true, data: { locale: I18n.locale, destination: { latitude: latitude, longitude: longitude } }, :target => "_blank" do %>
            <i class="fa fa-location-arrow"></i><abbr><%= street %>, <%= zipcode %> <%= city %></abbr>
          <% end %>
        </div>
        <div class="container-code">
          <p class="box-code-legend">Rendez-vous en magasin pour nous rencontrer et profiter du bon plan !</p>
        </div>
      </figure>
    </div>
  </div>
</div>

app/views/pro/perks/modals/_perk_offline_mobile.html.erb
<div class="use-overlay hidden">
  <div class="flip-container-mobile">
    <div class="flipper-mobile">
      <!-- FRONT CARD-->
      <figure class="front">
        <!-- CLOSE BUTTON-->
        <button type="button" class="close-button">&times;</button>
        <!-- ILLUSTRATION-->
        <div class="wrapper">
          <%= render "shared/icons/thumb_like" %>
        </div>
        <span class="business-name"><%= @perk.business.name %></span>
        <!-- ITINARY -->
        <div class="itinary">
          <%= link_to "http://maps.google.com/maps", class: "", id:"link-map", disabled: true, data: { locale: I18n.locale, destination: { latitude: latitude, longitude: longitude } }, :target => "_blank" do %>
            <i class="fa fa-location-arrow"></i><abbr><%= street %>, <%= zipcode %> <%= city %></abbr>
          <% end %>
        </div>
        <div class="container-legend">
          <% if @perk.appel %>
            <p>Attention, ce bon plan est valable une seule fois, n’accédez à votre carte qu’une fois en magasin !</p>
          <% else %>
            <p>À montrer en magasin !</p>
          <% end %>
        </div>
        <!-- SHOW MEMBER CARD -->
        <div class="container-code">
          <div class="show-card">
            <%= simple_form_for :use, url: perk_uses_path(params[:perk_id]), method: :post, remote: true, authenticity_token: true do |f| %>
              <%= f.input :perk_id, as: :hidden, input_html: {value: params[:perk_id]} %>
              <%= f.submit "J'accède à ma carte", class: "btn-show-card" %>
            <% end %>
          </div>
        </div>
      </figure>

      <!-- BACK CARD -->
      <figure class="back">
        <!-- MEMBER CARD -->
        <div class="member-card">
          <div class="validation-date">
            <span>Le <%= I18n.l DateTime.now.to_date, format: :short %> <%= DateTime.now.year %></span>
          </div>

          <div class="logo">
            <%= image_tag 'logo-classic.png' %>
          </div>

          <div class="member-info">
            <%= image_tag (current_user.picture? ? current_user.picture.url(:avatar) : "profile.png"), class: "img-circle user"%>
            <% if current_user.name.present? %>
              <span class="user"><%= current_user.name %></span>
            <% else %>
              <span class="user"><%= current_user.first_name %> <%= current_user.last_name %></span>
            <% end %>
            <% if current_user.cause_id.present? %>
                <span class="cause"><%= current_user.cause.name %></span>
                <%= image_tag (current_user.cause.logo), class: "img-circle cause" %>
            <% end %>
          </div>
        </div>

        <!-- FEEDBACK USE -->
        <!-- <div class="container-feedback"></div> -->
      </figure>
    </div>
  </div>
</div>

app/views/pro/perks/modals/_perk_online.html.erb
<div class="use-overlay hidden">
  <div class="flip-container-mobile">
    <div class="flipper-mobile">
      <!-- FRONT CARD-->
      <figure class="front">
        <!-- CLOSE BUTTON-->
        <button type="button" class="close-button">&times;</button>
        <!-- ILLUSTRATION-->
        <div class="wrapper">
          <%= render "shared/icons/browser" %>
        </div>
        <span class="business-name"><%= @perk.business.name %></span>
        <!-- CTA -->
        <div class="itinary">
          <%= link_to "#{@business.url}", class: "send-to-shop", target: "_blank" do %>
            <i class="fa fa-globe"></i>
            <% if @business.url.size > 28 %>
              <abbr><%= truncate(@business.url, length: 28) %></abbr>
            <% else %>
              <abbr><%= @business.url %></abbr>
            <% end %>
          <% end %>
        </div>
        <div class="container-code">
          <p class="box-code-legend">Copiez ce code pour bénéficier de réductions sur le site du commerçant :</p>
          <span class="online-code"><%= Perk.find(params[:perk_id]).perk_code.upcase %></span>
          <% if @perk.appel %>
            <p class="box-code-legend">Attention, ce bon plan n'est valable qu'une seule fois !</p>
          <% end %>
        </div>
        <%= simple_form_for :use, url: perk_uses_path(params[:perk_id], online: true), method: :post, remote: true, authenticity_token: true, html: { id: :create_use } do |f| %>
          <%= f.input :perk_id, as: :hidden, input_html: {value: params[:perk_id]} %>
          <%= f.submit "J'utilise", class: "btn-create-use", :style => "display: none;" %>
        <% end %>
      </figure>
      <!-- BACK CARD -->
      <figure class="back">
        <div class="container-feedback"></div>
      </figure>
    </div>
  </div>
</div>

<% content_for :after_js do %>
  <script>
    $(document).ready(function(){

      $('.send-to-shop').click(function() {
        $('.btn-create-use').click();
      });

    });
  </script>
<% end %>