config/routes.rb
Rails.application.routes.draw do

  # mount ForestLiana::Engine => '/forest'
  ActiveAdmin.routes(self)

  # ROOT TO LANDING WEBSITE
  if Rails.env.development?
    devise_scope :user do
      root to: 'devise/sessions#new'
    end
  else
    root to: redirect("http://cforgood.com")
  end

  get 'notre_charte',             to: 'pages#charte'
  get 'cgu',                      to: 'pages#cgu'
  get 'faq_connect',              to: 'pages#faq_connect'
  put 'newsletter',               to: 'pages#newsletter'

  resources :contact_forms, only: [:new, :create]

  # ROOT TO APP CFORGOOD
  resources :businesses, only: [:index, :show]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', passwords: :passwords }, path: '', path_names: {:sign_in => 'signin', :sign_up => 'signup'}
  devise_scope :user do
    get 'signin',                   to: 'devise/sessions#new'
    post 'signin',                  to: 'devise/sessions#create'
    get 'signup',                   to: 'devise/registrations#new'
    post 'signup',                  to: 'devise/registrations#create'
    get 'signup_trial',             to: 'devise/registrations#new_gift'
    post 'signup_trial',            to: 'devise/registrations#create_gift'
    get 'signup_gift',              to: 'devise/registrations#new_gift'
    post 'signup_gift',             to: 'devise/registrations#create_gift'
    get 'signup_beneficiary',       to: 'devise/registrations#new_gift'
    post 'signup_beneficiary',      to: 'devise/registrations#create_gift'
    get "member/sent_mail",         to: "devise/passwords#sent_mail"
    put "member/update_cause",      to: "member/registrations#update_cause"
    put "member/update_profile",    to: "member/registrations#update_profile"
    put "member/stop_subscription", to: "member/registrations#stop_subscription"
  end

  namespace :member do
    resources :users, only: [:show, :update] do
      get "dashboard",  to: "dashboard#dashboard"
      get "profile",    to: "dashboard#profile"
      get "ambassador", to: "dashboard#ambassador"
      get "gift",       to: "dashboard#gift"
    end
    get "subscribe_gift", to: "subscribe#gift"
    resources :subscribe, only: [:new, :create, :update, :destroy]
    resources :perks, only: [:show]
  end

  get "map", to: "member/dashboard#dashboard"

  resources :users do
    resources :beneficiaries, only: [:create, :update]
  end

  devise_for :businesses, path: :pro, controllers: { passwords: :passwords }
  devise_scope :business do
    get "pro/sent_mail",        to: "devise/passwords#sent_mail"
    put "pro/update_business",  to: "pro/registrations#update_business"
  end

  namespace :pro do
    resources :businesses, only: [:show, :update, :new, :create] do
      resources :addresses
      resources :perks, only: [:index, :new, :create, :update]
      get 'dashboard',  to: 'dashboard#dashboard'
      post 'impersonation', to: 'dashboard#set_impersonation'
      get "profile",    to: "dashboard#profile"
      get "supervisor_dashboard", to: "dashboard#supervisor_dashboard"
    end
    resources :perks, only: [:show, :edit, :update, :destroy]
    resources :addresses, only: [:update]

    resources :activate, only: [:update, :destroy]
  end

  # namespace :asso do
  resources :causes, only: [:index, :show]
  #   get 'dashboard', to: 'dashboard#dashboard'
  # end

  resources :perks do
    resources :uses, only: [:create, :update]
  end

  resources :addresses do
    resources :timetables, only: [:create, :update]
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/pro/addresses_controller.rb
class Pro::AddressesController < Pro::ProController

  before_action :find_address, only: [:edit, :update, :destroy]
  before_action :find_business, only: [:index, :new, :create, :update]

  def index
    @addresses = policy_scope(Address)
  end

  def create
    @address = @business.addresses.build(address_params)
    authorize @address
    respond_to do |format|
      if @address.save
        format.html { redirect_to pro_business_profile_path(@business) }
        format.js {}
      else
        format.html { redirect_to pro_business_profile_path(@business) }
        format.js {}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to pro_business_profile_path(@business) }
        format.js {}
      else
        format.html { render :edit }
        format.js {}
      end
    end
  end

  private

  def find_address
    @address = Address.find(params[:id])
    authorize @address
  end

  def find_business
    @business = Business.find(params[:business_id])
  end

  def address_params
    params.require(:address).permit(:day, :business_id, :start_time, :start_time_hour, :start_time_min, :end_time, :end_time_hour, :end_time_min, :street, :zipcode, :city, :active)
  end

end

app/controllers/pro/businesses_controller.rb
class Pro::BusinessesController < Pro::ProController

  skip_after_action :verify_authorized

  def new
    if current_impersonation
      @error = "Vous essayez de créer un commerce, nous vous avons déconnecté de #{current_impersonation.name}"
    end
    session[:impersonate_id] = nil
    @business = Business.new
  end

  def create
    @business = current_business.businesses.build(business_params)
    @business.password = 'cforgood'
    if @business.save
      session[:impersonate_id] = @business.id
      redirect_to pro_business_profile_path(current_business)
    else
      @error = "Echec de la création du commerce"
      render :new
    end
  end

  private

  def business_params
    params.require(:business).permit(:name, :email, :city, :zipcode, :business_category_id)
  end
end

app/controllers/pro/dashboard_controller.rb
class Pro::DashboardController < Pro::ProController

  skip_after_action :verify_authorized, only: :set_impersonation
  before_action :find_business, only: [:dashboard, :profile]

  def set_impersonation
    if current_business.supervising?(params[:impersonate_id])
      session[:impersonate_id] = params[:impersonate_id]
    else
      session[:impersonate_id] = nil
    end
    redirect_to pro_business_dashboard_path(current_business)
  end

  def dashboard
    @perks = @business.perks
    authorize @business
  end

  def profile
    5.times{ @business.addresses.build }
    authorize @business
  end

  def supervisor_dashboard
    @business = current_business
    # A modifier !!!
    # @perks = @business.businesses_perks
    authorize @business

    @geojson = {"type" => "FeatureCollection", "features" => []}

    if current_business.admin
      @businesses = Business.all.includes(:addresses, :business_category, :perks).eager_load(:businesses_perks, :businesses_perks_uses)
    else
      @businesses = @business.businesses.includes(:addresses, :business_category, :perks).eager_load(:businesses_perks, :businesses_perks_uses)
    end

    @businesses.each do |business|
      # BUSINESS ADDRESSES
      addresses = []
      # Main shop address
      addresses << [0, business.longitude, business.latitude, business.street] if business.shop
      # Other addresses
      business.addresses.each do |address|
        # shop
        addresses << [address.id, address.longitude, address.latitude, address.street] if business.shop and !address.day.present?
        # itinerant
        addresses << [address.id, address.longitude, address.latitude, address.street] if business.itinerant and address.day.present?
      end

      # LOAD ADDRESSES
      addresses.uniq!
      addresses.each do |address|
        @geojson["features"] << {
          "type": 'Feature',
          "geometry": {
            "type": 'Point',
            "coordinates": [address[1], address[2]],
          },
          "properties": {
            "marker-symbol": business.business_category.marker_symbol
          }
        }
      end
    end
  end

  private

  def find_business
    id = session[:impersonate_id] || params[:business_id]
    @business = Business.includes(:manager).find(id)
  end
end

app/controllers/pro/perks_controller.rb
class Pro::PerksController < Pro::ProController

  before_action :find_perk, only: [:edit, :update, :destroy]
  before_action :find_business, only: [:index, :new, :create, :edit]

  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def index
    if session[:impersonate_id]
      @perks = Perk.where(business_id: session[:impersonate_id]).undeleted
    else
      @perks = policy_scope(Perk).undeleted
    end
  end

  def new
    @perk = Perk.new
    authorize @perk
  end

  def create
    @perk = @business.perks.build(perk_params)
    authorize @perk

    respond_to do |format|
      if @perk.save
        format.html { redirect_to pro_business_perks_path(current_business) }
        format.js {}
      else
        format.html { render :new }
        format.js {}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @perk.update(perk_params)
        format.html { redirect_to pro_business_perks_path(current_business) }
        format.js {}
      else
        format.html { render :edit }
        format.js {}
      end
    end
  end

  def destroy
    if @perk.nb_views > 0 || @perk.uses.count > 0 || @perk.created_at < Date.today
      @perk.deleted!
    else
      @perk.destroy
    end
    redirect_to pro_business_perks_path(current_business)
  end

  private

  def find_perk
    @perk = Perk.find(params[:id])
    # authorize @perk
  end

  def find_business
    id = session[:impersonate_id] || params[:business_id] || current_business.id
    @business = Business.find(id)
  end

  def perk_params
    params.require(:perk).permit(:name, :description, :perk_detail_id, :times, :start_date, :start_date_date, :start_date_hour, :start_date_min, :end_date, :end_date_date, :end_date_hour, :end_date_min, :all_day, :perk_code, :picture, :active, :appel, :durable, :flash)
  end
end

app/controllers/pro/pro_controller.rb
class Pro::ProController < ActionController::Base

  layout 'application'

  before_action :authenticate_business!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :devise_controller?
  after_action :verify_policy_scoped, only: :index, unless: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(pro_business_dashboard_path(current_business))
  end

  def pundit_user
    current_business
  end

  def current_impersonation
    return nil unless session[:impersonate_id].present?
    @current_impersonation ||= Business.find(session[:impersonate_id])
  end
end

app/controllers/pro/registrations_controller.rb
class Pro::RegistrationsController < Devise::RegistrationsController

  def update_business
    if session[:impersonate_id].present?
      @business = Business.find(session[:impersonate_id])
    else
      @business = current_business
    end
    if business_params[:password].present?
      @business.update(business_params)
      # sign_in(current_business, bypass: true)
    else
      @business.update_without_password(business_params)
    end
    respond_to do |format|
      format.html {redirect_to pro_business_profile_path(current_business) }
      format.js {}
    end
  end

  private

  def business_params
    params.require(:business).permit(:name, :street, :zipcode, :city, :url, :telephone, :email, :password, :description, :picture, :business_category_id, :facebook, :twitter, :instagram, :leader_picture,:leader_first_name, :leader_last_name, :leader_description, :leader_phone, :leader_email, :active, :shop, :online, :itinerant, addresses_attributes: [ :_destroy, :id, :active, :street, :zipcode, :city ])
  end
end

app/views/pro/perks/create.js.erb
if (<%= !@perk.errors.any? %>) {

  // DISCLAIMER - DISPLAYED
  $(".done-overlay").removeClass("hidden");

  window.setTimeout(function(){
    // DISCLAIMER - HIDDEN
    $(".done-overlay").addClass("hidden");
    window.location.href = "<%= pro_business_perks_path(current_business) %>";
  }, 3000);

} else {

  $(".alert").remove();
  $(document).find("form").prepend('<%= j render("components/error_messages", resource: @perk, formats: [:html]) %>');

}

app/views/pro/perks/edit.html.erb
<%= content_for(:title) do %>
<%= @perk.name %>
<% end %>
<%= content_for(:description) do %>
Modifiez votre Bon Plan
<% end %>

<div class="container-fluid admin">
  <!-- Sub Menu Sidebar -->
  <% if current_business.supervisor %>
    <%= render "pro/dashboard/shared/supervisor_sidebar" %>
  <% else %>
    <%= render "pro/dashboard/shared/sidebar" %>
  <% end %>
  <!-- Content - Statistics -->
  <div class="dashboard">
    <div class="dashboard-overlay hidden"></div>
    <div class="mobile-menu-overlay hidden"></div>
    <div class="form-perk-container">
      <%= render 'pro/perks/form/edit' %>
    </div>
  </div>
</div>

<% content_for :after_js do %>
  <script>
    $(document).ready(function() {
     $('#perk-tab').addClass('active');
    });
  </script>
<% end %>

app/views/pro/perks/index.html.erb
<%= content_for(:title) do %>
  <%= @business.name %>
<% end %>
<%= content_for(:description) do %>
  Consultez vos Bons Plans
<% end %>

<div class="container-fluid admin">
  <!-- Sub Menu Sidebar -->
  <% if current_business.supervisor %>
    <%= render "pro/dashboard/shared/supervisor_sidebar" %>
  <% else %>
    <%= render "pro/dashboard/shared/sidebar" %>
  <% end %>
  <!-- Content - Statistics -->
  <div class="dashboard">
    <div class="mobile-menu-overlay hidden"></div>
    <div class="admin-perks">
      <%= image_tag('logopouce.png', class: 'logo-title') %>
      <span class="view-title">Mes bons plans</span>
      <% if current_business.supervisor && !current_impersonation %>
        <%= render 'components/popups/supervisor_without_impersonate' %>
      <% elsif @perks.count == 0 %>
        <%= render 'components/popups/empty_perks_index' %>
      <% else %>
        <% @perks.reverse.each do |perk| %>
          <div class="admin-perk-card">
            <!-- PERK MAIN INFOS -->
            <div class="perk-details">
              <div class="perk-title">
                <%= perk.name.upcase %>
                <% if perk.appel %>
                  <i class="fa fa-gift pro-card-perk-flash"></i>
                <% end %>
                <% if perk.durable %>
                  <i class="fa fa-repeat pro-card-perk-flash"></i>
                <% end %>
                <% if perk.flash %>
                  <i class="fa fa-bolt pro-card-perk-flash"></i>
                <% end %>
                <!-- CREATION DATE -->
                <div class="perk-creation-date">
                  <span>Créé : <em>le <%= perk.created_at.strftime("%d %b %Y") %></em></span>
                </div>
                <!-- PERK CODE -->
                <% if PerkDetail.find(perk.perk_detail_id).name != "carte" %>
                  <span class="perk-code">Code client : <%= perk.perk_code %></span>
                <% end %>
              </div>

              <div class="perk-content">
                <%= perk.description %>
                <div class="perk-date">
                  <% if perk.appel %>
                    <span>Bon Plan de bienvenue</span>
                  <% elsif perk.durable %>
                     <span>Bon Plan durable</span>
                  <% else %>
                    <% if perk.times > 0 %>
                      <span><i class="fa fa-barcode"></i><%= perk.times - Use.where(perk_id: perk.id).count %> restants</span>
                    <% end %>
                    <span><i class="fa fa-calendar-check-o"></i><%= render(partial: "components/perk_flash_period", locals: { start_date: perk.start_date, end_date: perk.end_date }) %></span>
                  <% end %>
                </div>
                <!-- PERK STATS -->
                <div class="perk-stats">
                  <ul>
                    <li>Vues <strong><%= perk.nb_views %></strong></li>
                    <li>Utilisations <strong><%= perk.uses.count %></strong></li>
                    <li>Clients <strong><%= perk.uses.select(:user_id).distinct.count %></strong></li>
                  </ul>
                </div>
              </div>
            </div>
            <!-- PERK ACTIVATION -->
            <div class="perk-activation">
              <span>Désactiver / Activer</span>
              <input class="tgl tgl-light" id="<%= perk.id %>" type="checkbox" <%= 'checked="checked"' if perk.active %>>
              <label class="tgl-btn" for="<%= perk.id %>"></label>
              <%= simple_form_for :perk, url: pro_perk_path(perk.id), method: :patch, html: { id: "update_perk_#{perk.id}", class: "hidden" } do |f| %>
                <%= f.input :active, as: :hidden, input_html: { value: !perk.active } %>
                <%= f.submit "", :style => "display: none;" %>
              <% end %>
            </div>
            <div class="perk-actions">
              <!-- PERK PREVIEW -->
              <%= link_to business_path(@business, perk_id: perk.id), target: "_blank", class: "perk-preview" do %>
                <i class="fa fa-eye"></i>
              <% end %>
              <!-- PERK EDIT -->
              <%= link_to edit_pro_perk_path(perk), class: "perk-status" do %>
                <i class="fa fa-pencil"></i>
              <% end %>
              <!-- PERK DELETION -->
              <a class="perk-delete-button perk-deletion" id="perk_<%= perk.id %>"><i class="fa fa-trash-o"></i></a>
              <div class="hidden">
                <%= simple_form_for :perk, url: pro_perk_path(perk), method: :delete, html: { id: "delete_perk_#{perk.id}" } do |f| %>
                <%= f.submit "", :style => "display: none;" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'pro/perks/form/delete_confirmation' %>
<%= render 'pro/perks/form/last_perk_deleted' %>
<%= render 'pro/perks/form/last_perk_desactivated' %>

<% content_for :after_js do %>
  <script>
    $(document).ready(function() {
      $(':checkbox').change(function(e) {
        e.preventDefault();
        var idPerk = $(this).val("form").attr('id');
        var updatePerk = "update_perk_" + idPerk;
        if ($('#' + idPerk).attr('checked') == 'checked' && <%= current_business.perks.active.count == 1 %>) {
          $('.id-perk').html(updatePerk);
          $(".last-perk-desactivated").toggleClass("hidden");
        } else {
          $('#' + updatePerk).submit();
        }
      });

      $(".perk-delete-button").on("click", function() {
        var deletePerk = "delete_" + ($(this).val("div").attr('id'));
        $(".business-button").addClass(deletePerk);
        if (<%= current_business.perks.active.count == 1 %>) {
          $(".last-perk-deleted").toggleClass("hidden");
        } else {
          $(".delete-confirmation").toggleClass("hidden");
        }
      });

    });
  </script>
<% end %>

app/views/pro/perks/new.html.erb
<%= content_for(:title) do %>
<%= @business.name %>
<% end %>
<%= content_for(:description) do %>
Créez un nouveau Bon Plan
<% end %>

<div class="container-fluid admin">
  <!-- Sub Menu Sidebar -->
  <% if current_business.supervisor %>
    <%= render "pro/dashboard/shared/supervisor_sidebar" %>
  <% else %>
    <%= render "pro/dashboard/shared/sidebar" %>
  <% end %>
  <!-- Content - Statistics -->
  <div class="dashboard">
    <% if current_business.supervisor && !current_impersonation %>
      <%= render 'components/popups/supervisor_without_impersonate' %>
    <% else %>
      <div class="dashboard-overlay hidden"></div>
      <div class="form-perk-container">
        <%= render 'pro/perks/form/create' %>
      </div>
    <% end %>
  </div>
</div>

app/views/pro/perks/update.js.erb
$(".alert").remove();

if (<%= !@perk.errors.any? %>) {

  // DISCLAIMER - DISPLAYED
  $(".done-overlay").removeClass("hidden");

  window.setTimeout(function(){
    // DISCLAIMER - HIDDEN
    $(".done-overlay").addClass("hidden");
    window.location.href = "<%= pro_business_perks_path(current_business) %>";
  }, 3000);

} else {

  $(document).find("form").prepend('<%= j render("components/error_messages", resource: @perk, formats: [:html]) %>');

}